### ISSUE TITLE
EXE Files appear to be malicious

### ISSUE THREAD

**Issue by frankzoldan** [ChrisRfr/PinUtil#3]
I scanned both EXE files with www.virustotal.com.
Three checks showed threats:
```
Bkav Pro W32.AIDetectMalware Cynet Malicious (score: 100)
MaxSecure Trojan.Malware.300983.susgen Rising Trojan.Generic@AI.90 (RDML:ZsNHfOR23ltxhjVNEaoINw)
SecureAge Malicious Trapmine Malicious.moderate.ml.score
```
I'd like to try your Application if you provide the source code so I could inspect an build it on my own.

**Comment by ChrisRfr** [comment]
These are false positives
You can also notify these "minor" antivirus so that the file can be scanned by their experts and report it as false positives, ex for [securage](https://www.secureage.com/support/report-false-positive) 

Related to the source file, see issue [Source of application? #1](https://github.com/ChrisRfr/PinUtil/issues/1)
